### ISSUE TITLE
多重背景的background

### ISSUE THREAD

**Issue by ceerqingting** [ceerqingting/issueBlog#9]
1. 同时定义多张图片背景
```css
 body {
      background: url('./img/01.jpg') no-repeat top center,
      url('./img/02.jpg') no-repeat top center;
  }
```
层级顺序为： 01.jpg在最顶层，后面依次往下排

2. 同时定义图片以及背景色
```css
 body {
      background: url('./img/01.jpg') no-repeat top center #ddd;
 }
```
3. 同时定义多张图片以及背景色
```css
   body {
      background-color: #ddd;
      background-repeat: no-repeat;
      background-image: url('./img/01.jpg'), url('./img/02.jpg');
      background-position: top center, bottom center;
    }
```
